batch_size: '128'
cross_trail: 'true'
data_dir: ./data_processed
dataset: seed_de_lds
dataset_path: D:/Work/Studio/PyCharm/PythonProject/DeepLearn/LibEER/data_utils/Dataset/SEED
device: cuda
epochs: '40'
experiment_mode: subject-dependent
feature_type: de_lds
fold_num: '5'
fold_shuffle: 'true'
front: '9'
high_pass: '50'
log_dir: ./log/
loss_func: crossEntropyLoss
low_pass: '0.3'
lr: '0.001'
metric_choose: acc
metrics:
- acc
- macro-f1
- micro-f1
- precision
- recall
num_workers: '4'
onehot: 'on'
only_seg: 'on'
output_dir: ./result/
overlap: '0'
sample_length: '1'
seed: '1'
setting: seed_sub_dependent_front_back_setting
split_type: front-back
stride: '1'
test_size: '0.2'
time_window: '1'
val_size: '0.2'
