batch_size: '256'
cross_trail: 'true'
data_dir: ./data_processed
dataset: seed_raw
dataset_path: D:/Work/Studio/PyCharm/PythonProject/DeepLearn/LibEER/data_utils/Dataset/SEED
device: cuda
epochs: '100'
experiment_mode: subject-dependent
feature_type: de_lds
fold_num: '5'
fold_shuffle: 'true'
front: '9'
high_pass: '50'
log_dir: ./log/
loss_func: crossEntropyLoss
low_pass: '0.3'
lr: '0.001'
metric_choose: macro-f1
metrics:
- acc
- macro-f1
num_workers: '4'
onehot: 'on'
only_seg: 'on'
output_dir: ./result/
overlap: '0'
sample_length: '200'
seed: '2024'
setting: seed_sub_independent_train_val_test_setting
split_type: front-back
stride: '200'
test_size: '0.2'
time_window: '1'
val_size: '0.2'
