batch_size: 128
bounds: null
checkpoint: null
cross_trail: 'true'
data_dir: ./data_processed
dataset: seed_de_lds
dataset_path: D:/Work/Studio/PyCharm/PythonProject/DeepLearn/LibEER/data_utils/Dataset/SEED
device: cuda
eog_clean: false
epochs: 40
eval: false
experiment_mode: subject-dependent
feature_type: de_lds
fold_num: 5
fold_shuffle: 'true'
front: 9
high_pass: 50
keep_dim: false
label_used: null
log_dir: ./log/
loss_func: crossEntropyLoss
low_pass: 0.3
lr: 0.001
metric_choose: acc
metrics:
- acc
model: TSception
normalize: true
num_workers: 4
onehot: false
only_seg: false
output_dir: ./result/
overlap: 0
pr: null
resume: false
resume_epoch: 0
sample_length: 1
save_data: false
seed: 1
sessions: null
setting: seed_sub_dependent_front_back_setting
split_type: front-back
sr: null
stride: 1
test_size: 0.2
time_window: 1
val_size: 0.2
