# Generated by Django 6.0 on 2026-01-12 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("dataset", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("experiment_mode", models.CharField(max_length=50)),
                ("split_type", models.CharField(max_length=50)),
                ("batch_size", models.IntegerField(default=256)),
                ("epochs", models.IntegerField(default=100)),
                ("learning_rate", models.FloatField(default=0.001)),
                ("sample_length", models.IntegerField(default=200)),
                ("stride", models.IntegerField(default=200)),
                ("only_seg", models.BooleanField(default=True)),
                ("onehot", models.BooleanField(default=True)),
                ("metrics", models.JSONField(default=list)),
                ("metric_choose", models.CharField(default="macro-f1", max_length=50)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="未命名训练任务", max_length=200)),
                ("dataset", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("experiment_mode", models.CharField(max_length=50)),
                ("split_type", models.CharField(max_length=50)),
                ("batch_size", models.IntegerField(default=256)),
                ("epochs", models.IntegerField(default=100)),
                ("learning_rate", models.FloatField(default=0.001)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("paused", "已暂停"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_epoch", models.IntegerField(default=0)),
                ("total_epochs", models.IntegerField(default=0)),
                ("progress", models.FloatField(default=0.0)),
                ("train_acc", models.FloatField(default=0.0)),
                ("train_loss", models.FloatField(default=0.0)),
                ("train_f1", models.FloatField(default=0.0)),
                ("val_acc", models.FloatField(default=0.0)),
                ("val_loss", models.FloatField(default=0.0)),
                ("val_f1", models.FloatField(default=0.0)),
                ("best_val_acc", models.FloatField(default=0.0)),
                ("best_val_f1", models.FloatField(default=0.0)),
                ("best_test_acc", models.FloatField(default=0.0)),
                ("best_test_f1", models.FloatField(default=0.0)),
                ("log_file", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "result_file",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "model_checkpoint",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_config", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="modelVisual_status_558153_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="modelVisual_created_fa0af9_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="modelVisual_user_id_7c2cde_idx",
                    ),
                ],
            },
        ),
    ]
