# Generated by Django 6.0 on 2026-01-16 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelVisualization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelCategory",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "模型分类",
                "verbose_name_plural": "模型分类",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("paper_url", models.URLField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("is_implemented", models.BooleanField(default=False)),
                ("train_file", models.CharField(blank=True, max_length=500)),
                ("model_class", models.CharField(blank=True, max_length=500)),
                ("config_file", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_recommended", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="modelVisualization.modelcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "训练模型",
                "verbose_name_plural": "训练模型",
                "ordering": ["category__order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="ModelConfigTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("config_data", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("use_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="modelVisualization.trainingmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型配置模板",
                "verbose_name_plural": "模型配置模板",
                "ordering": ["-is_default", "-use_count", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="trainingmodel",
            index=models.Index(
                fields=["category", "is_active"], name="modelVisual_categor_82b600_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingmodel",
            index=models.Index(
                fields=["is_implemented"], name="modelVisual_is_impl_6b7aa3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingmodel",
            index=models.Index(
                fields=["is_recommended"], name="modelVisual_is_reco_f950bd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modelconfigtemplate",
            unique_together={("model", "name", "user")},
        ),
    ]
